### ISSUE TITLE
Cannot call method "getFieldNames" on alfresco 4.2f

### ISSUE THREAD

**Issue by jforeman** [deas/fme-alfresco-extdl#14]
After installing the plugin (using the master branch), I go to create a new datalist, create a new item and receive the following error:
05160003 Wrapped Exception (with status template): 05160228 Failed to execute script 'classpath*:alfresco/extension/templates/webscripts/org/alfresco/slingshot/datalists/data.post.json.js': 05160227 TypeError: Cannot call method "getFieldNames" of undefined (jar:file:/opt/alfresco-4.2.f/tomcat/webapps/alfresco/WEB-INF/lib/fme-alfresco-extdl-repo-1.2.jar!/alfresco/extension/templates/webscripts/org/alfresco/slingshot/datalists/data.post.json.js#825)

**Comment by tass01024** [comment]
this is fixed in version 1.3
