### ISSUE TITLE
Datalist section layout gets corrupted

### ISSUE THREAD

**Issue by ralgozino** [deas/fme-alfresco-extdl#16]
Hello!

 Adding this plugins brakes the datalist page layout. I'm using the plugin in alfresco 5.0.a, can't tell in previous versions.

 My monitor is using FullHD resolution, tested on Firefox.
![issue](https://cloud.githubusercontent.com/assets/6362698/4526841/e8c08306-4d62-11e4-81d9-54a601fc289b.png)

**Comment by tass01024** [comment]
This should be closed
