### ISSUE TITLE
date-range filter search seems broken in solr

### ISSUE THREAD

**Issue by billerby** [deas/fme-alfresco-extdl#22]
When filtering by a date-range I got some strange results. Debugging the filterQuery reveals that the query looks like this:

`+PARENT:"workspace://SpacesStore/c8c641b8-ab25-4962-8782-5d448822914d" -TYPE:"folder" +@demo\:myDate:[2015-02-06T00:00:00+01:00 TO 2015-02-07T00:00:00+01:00] "`

This should not give any results. However changing the date to not use a timezone offset like this:
`+PARENT:"workspace://SpacesStore/c8c641b8-ab25-4962-8782-5d448822914d" -TYPE:"folder" +@demo\:myDate:[2015-02-06T00:00:00.000 TO 2015-02-07T00:00:00.000] "`

will give a correct result with one hit.

**Comment by tass01024** [comment]
Yes, i think your right, i think this fork has a fix ... wonder if it is being merged back?

https://github.com/schminkel/fme-alfresco-extdl

**Comment by deas** [comment]
Never seen that fork before.  :)

**Comment by billerby** [comment]
Ok, maybe we should check if that fix works in lucene as well before merging that into this codebase..  :) I'll give it a try and reports back, will see if I can make a "clean pull request" for just that feature.

**Comment by tass01024** [comment]
No i just saw it a couple of days ago, it seems to be general impr. 

For the date issues maybe we need: utils.fromISO8601(date) in data.post.json.js

**Comment by billerby** [comment]
Tried that, problem is that the date there is a string, so I guess it will need some string manipulations.

**Comment by billerby** [comment]
Ok, tried their solution in both solr and lucene. Works good on both.

**Comment by tass01024** [comment]
Super!! Is that what is done here: https://github.com/schminkel/fme-alfresco-extdl/blob/master/fme-alfresco-extdl-repo/src/main/resources/alfresco/extension/templates/webscripts/org/alfresco/slingshot/datalists/extdl-filters.lib.js

**Comment by billerby** [comment]
Yes, I'll make a pull request soon.
