### ISSUE TITLE
"Created by Me" not working

### ISSUE THREAD

**Issue by figroc** [deas/fme-alfresco-extdl#4]
I installed the extension in Alfresco Community 4.2.c.

Error message pops up: 06250003 Wrapped Exception (with status template): 06250143 Failed to execute script 'classpath*:alfresco/extension/templates/webscripts/org/alfresco/slingshot/datalists/data.post.json.js': 06250142 TypeError: Cannot call method "getFieldNames" of undefined (jar:file:/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/lib/fme-alfresco-extdl-repo-1.2.jar!/alfresco/extension/templates/webscripts/org/alfresco/slingshot/datalists/data.post.json.js#825)

I'm still digging the js files. Does anyone get any clue?

**Comment by tass01024** [comment]
this is fixed in version 1.3
