### ISSUE TITLE
Filter for ID field in TopicList not working

### ISSUE THREAD

**Issue by IljaSchumacher** [deas/fme-alfresco-extdl#6]
No hits when trying to filter for an issue ID.

Result is an empty set.
This is the Query string POSTed by the browser.

{\"fields\":[\"dl_itemId\",\"dl_issueID\",\"cm_title\",\"dl_issueAssignedTo\",\"dl_issueStatus\",\"dl_issuePriority\",\"cm_description\",\"dl_issueDueDate\",\"cm_attachments\",\"fm_discussable\"],\"filter\":{\"filterId\":\"filterform\",\"filterData\":{\"prop_dl_itemId\":\"1\",\"prop_cm_title\":\"\",\"prop_cm_description\":\"\",\"dl_assigneeFullName\":\"\",\"prop_dl_issueStatus\":\"Not Started,In Progress,Complete,On Hold\",\"prop_dl_issuePriority\":\"High,Low,Normal\",\"prop_cm_creator\":\"\",\"prop_dl_issueDueDate-date-range\":\"\",\"prop_cm_created-date-range\":\"\"}}}"

No Errors are logged by the server

Also Solr complains about non-incremental updates of TYPE in modelType Datalist.
Disabling model validation by the modelDictionaryType property doValidation in the alfresco policy-context.xml did not help.
Unfortunately Solr has no means to disable Model Validation as you can see in the AlfrescoSolrDataModel.class found here http://svn.alfresco.com/repos/alfresco-open-mirror/alfresco/HEAD/root/projects/solr/source/java/org/alfresco/solr/AlfrescoSolrDataModel.java.

**Comment by tass01024** [comment]
this is fixed in version 1.3
